LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)

$(info CA build)
$(info MTKCAM_TARGET_BOARD_PLATFORM = $(MTKCAM_TARGET_BOARD_PLATFORM))
$(info MTK_CAM_GENIEZONE_SUPPORT = $(MTK_CAM_GENIEZONE_SUPPORT))
$(info test)

ifeq ($(MTKCAM_TARGET_BOARD_PLATFORM), $(filter $(MTKCAM_TARGET_BOARD_PLATFORM),mt6765 mt6768 mt6781 mt6785 mt6853 mt6873 mt6885 mt6893 mt6833 mt6877 mt6855 common))
ifeq ($(MTK_CAM_GENIEZONE_SUPPORT), yes)
LOCAL_MODULE := libispcameraca
LOCAL_MODULE_TAGS := optional
LOCAL_PROPRIETARY_MODULE := true

LOCAL_SHARED_LIBRARIES += liblog
LOCAL_SHARED_LIBRARIES += libion libion_mtk
LOCAL_SHARED_LIBRARIES += libcutils
LOCAL_SHARED_LIBRARIES += libdmabufheap
LOCAL_SHARED_LIBRARIES += libgz_uree
LOCAL_WHOLE_STATIC_LIBRARIES += libispcameraca_mtee

$(info LOCAL_WHOLE_STATIC_LIBRARIES = $(LOCAL_WHOLE_STATIC_LIBRARIES) )

include $(BUILD_SHARED_LIBRARY)

endif
endif
