/* Copyright Statement:
 *
 * This software/firmware and related documentation ("MediaTek Software") are
 * protected under relevant copyright laws. The information contained herein is
 * confidential and proprietary to MediaTek Inc. and/or its licensors. Without
 * the prior written permission of MediaTek inc. and/or its licensors, any
 * reproduction, modification, use or disclosure of MediaTek Software, and
 * information contained herein, in whole or in part, shall be strictly
 * prohibited.
 *
 * MediaTek Inc. (C) 2010. All rights reserved.
 *
 * BY OPENING THIS FILE, RECEIVER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
 * THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE")
 * RECEIVED FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO RECEIVER
 * ON AN "AS-IS" BASIS ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL
 * WARRANTIES, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE OR
 * NONINFRINGEMENT. NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY WHATSOEVER WITH
 * RESPECT TO THE SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY,
 * INCORPORATED IN, OR SUPPLIED WITH THE MEDIATEK SOFTWARE, AND RECEIVER AGREES
 * TO LOOK ONLY TO SUCH THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO.
 * RECEIVER EXPRESSLY ACKNOWLEDGES THAT IT IS RECEIVER'S SOLE RESPONSIBILITY TO
 * OBTAIN FROM ANY THIRD PARTY ALL PROPER LICENSES CONTAINED IN MEDIATEK
 * SOFTWARE. MEDIATEK SHALL ALSO NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE
 * RELEASES MADE TO RECEIVER'S SPECIFICATION OR TO CONFORM TO A PARTICULAR
 * STANDARD OR OPEN FORUM. RECEIVER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S
 * ENTIRE AND CUMULATIVE LIABILITY WITH RESPECT TO THE MEDIATEK SOFTWARE
 * RELEASED HEREUNDER WILL BE, AT MEDIATEK'S OPTION, TO REVISE OR REPLACE THE
 * MEDIATEK SOFTWARE AT ISSUE, OR REFUND ANY SOFTWARE LICENSE FEES OR SERVICE
 * CHARGE PAID BY RECEIVER TO MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE.
 *
 * The following software/firmware and/or related documentation ("MediaTek
 * Software") have been modified by MediaTek Inc. All revisions are subject to
 * any receiver's applicable license agreements with MediaTek Inc.
 */

#ifndef __SENINF_TEE_COMMON_H__
#define __SENINF_TEE_COMMON_H__

#include <stdint.h>

#define SENINF_TEE_REG_ADDR_BASE  0x1A001000
#define SENINF_TEE_REG_MAP_REGION 0xA000
#define SENINF_MUX_MAX_NUM 22
#define SENINF_CAM_MUX_MAX_NUM 23

typedef enum {
    SENINF_TEE_REG_ADDR_SENINF_TOP_MUX_CTRL_0     = 0x0010,
    SENINF_TEE_REG_ADDR_SENINF_TOP_MUX_CTRL_1     = 0x0014,
    SENINF_TEE_REG_ADDR_SENINF_TOP_MUX_CTRL_2     = 0x0018,
    SENINF_TEE_REG_ADDR_SENINF_TOP_MUX_CTRL_3     = 0x001C,
    SENINF_TEE_REG_ADDR_SENINF_TOP_MUX_CTRL_4     = 0x0020,
    SENINF_TEE_REG_ADDR_SENINF_TOP_MUX_CTRL_5     = 0x0024,
    SENINF_TEE_REG_ADDR_SENINF_CAM0_MUX_CTRL      = 0x0400,
    SENINF_TEE_REG_ADDR_SENINF_CAM1_MUX_CTRL      = 0x0420,
    SENINF_TEE_REG_ADDR_SENINF_CAM2_MUX_CTRL      = 0x0440,
    SENINF_TEE_REG_ADDR_SENINF_CAM3_MUX_CTRL      = 0x0460,
    SENINF_TEE_REG_ADDR_SENINF_CAM4_MUX_CTRL      = 0x0480,
    SENINF_TEE_REG_ADDR_SENINF_CAM5_MUX_CTRL      = 0x04A0,
    SENINF_TEE_REG_ADDR_SENINF_CAM6_MUX_CTRL      = 0x04C0,
    SENINF_TEE_REG_ADDR_SENINF_CAM7_MUX_CTRL      = 0x04E0,
    SENINF_TEE_REG_ADDR_SENINF_CAM8_MUX_CTRL      = 0x0500,
    SENINF_TEE_REG_ADDR_SENINF_CAM9_MUX_CTRL      = 0x0520,
    SENINF_TEE_REG_ADDR_SENINF_CAM10_MUX_CTRL     = 0x0540,
    SENINF_TEE_REG_ADDR_SENINF_CAM11_MUX_CTRL     = 0x0560,
    SENINF_TEE_REG_ADDR_SENINF_CAM12_MUX_CTRL     = 0x0580,
    SENINF_TEE_REG_ADDR_SENINF_CAM13_MUX_CTRL     = 0x05A0,
    SENINF_TEE_REG_ADDR_SENINF_CAM14_MUX_CTRL     = 0x05C0,
    SENINF_TEE_REG_ADDR_SENINF_CAM15_MUX_CTRL     = 0x05E0,
    SENINF_TEE_REG_ADDR_SENINF_CAM16_MUX_CTRL     = 0x0600,
    SENINF_TEE_REG_ADDR_SENINF_CAM17_MUX_CTRL     = 0x0620,
    SENINF_TEE_REG_ADDR_SENINF_CAM18_MUX_CTRL     = 0x0640,
    SENINF_TEE_REG_ADDR_SENINF_CAM19_MUX_CTRL     = 0x0660,
    SENINF_TEE_REG_ADDR_SENINF_CAM20_MUX_CTRL     = 0x0680,
    SENINF_TEE_REG_ADDR_SENINF_CAM21_MUX_CTRL     = 0x06A0,
    SENINF_TEE_REG_ADDR_SENINF_CAM22_MUX_CTRL     = 0x06C0,

    SENINF_TEE_REG_ADDR_SENINF1_MUX_CTRL_0        = 0x0D00,
    SENINF_TEE_REG_ADDR_SENINF1_MUX_CTRL_1        = 0x0D04,
    SENINF_TEE_REG_ADDR_SENINF1_MUX_OPT           = 0x0D08,
    SENINF_TEE_REG_ADDR_SENINF2_MUX_CTRL_0        = 0x0D00,
    SENINF_TEE_REG_ADDR_SENINF2_MUX_CTRL_1        = 0x0D04,
    SENINF_TEE_REG_ADDR_SENINF2_MUX_OPT           = 0x0D08,
    SENINF_TEE_REG_ADDR_SENINF3_MUX_CTRL_0        = 0x0D00,
    SENINF_TEE_REG_ADDR_SENINF3_MUX_CTRL_1        = 0x0D04,
    SENINF_TEE_REG_ADDR_SENINF3_MUX_OPT           = 0x0D08,
    SENINF_TEE_REG_ADDR_SENINF4_MUX_CTRL_0        = 0x0D00,
    SENINF_TEE_REG_ADDR_SENINF4_MUX_CTRL_1        = 0x0D04,
    SENINF_TEE_REG_ADDR_SENINF4_MUX_OPT           = 0x0D08,
    SENINF_TEE_REG_ADDR_SENINF5_MUX_CTRL_0        = 0x0D00,
    SENINF_TEE_REG_ADDR_SENINF5_MUX_CTRL_1        = 0x0D04,
    SENINF_TEE_REG_ADDR_SENINF5_MUX_OPT           = 0x0D08,
    SENINF_TEE_REG_ADDR_SENINF6_MUX_CTRL_0        = 0x0D00,
    SENINF_TEE_REG_ADDR_SENINF6_MUX_CTRL_1        = 0x0D04,
    SENINF_TEE_REG_ADDR_SENINF6_MUX_OPT           = 0x0D08,
    SENINF_TEE_REG_ADDR_SENINF7_MUX_CTRL_0        = 0x0D00,
    SENINF_TEE_REG_ADDR_SENINF7_MUX_CTRL_1        = 0x0D04,
    SENINF_TEE_REG_ADDR_SENINF7_MUX_OPT           = 0x0D08,
    SENINF_TEE_REG_ADDR_SENINF8_MUX_CTRL_0        = 0x0D00,
    SENINF_TEE_REG_ADDR_SENINF8_MUX_CTRL_1        = 0x0D04,
    SENINF_TEE_REG_ADDR_SENINF8_MUX_OPT           = 0x0D08,
    SENINF_TEE_REG_ADDR_SENINF9_MUX_CTRL_0        = 0x0D00,
    SENINF_TEE_REG_ADDR_SENINF9_MUX_CTRL_1        = 0x0D04,
    SENINF_TEE_REG_ADDR_SENINF9_MUX_OPT           = 0x0D08,
    SENINF_TEE_REG_ADDR_SENINF10_MUX_CTRL_0       = 0x0D00,
    SENINF_TEE_REG_ADDR_SENINF10_MUX_CTRL_1       = 0x0D04,
    SENINF_TEE_REG_ADDR_SENINF10_MUX_OPT          = 0x0D08,
    SENINF_TEE_REG_ADDR_SENINF11_MUX_CTRL_0       = 0x0D00,
    SENINF_TEE_REG_ADDR_SENINF11_MUX_CTRL_1       = 0x0D04,
    SENINF_TEE_REG_ADDR_SENINF11_MUX_OPT          = 0x0D08,
    SENINF_TEE_REG_ADDR_SENINF12_MUX_CTRL_0       = 0x0D00,
    SENINF_TEE_REG_ADDR_SENINF12_MUX_CTRL_1       = 0x0D04,
    SENINF_TEE_REG_ADDR_SENINF12_MUX_OPT          = 0x0D08,
    SENINF_TEE_REG_ADDR_SENINF13_MUX_CTRL_0       = 0x0D00,
    SENINF_TEE_REG_ADDR_SENINF13_MUX_CTRL_1       = 0x0D04,
    SENINF_TEE_REG_ADDR_SENINF13_MUX_OPT          = 0x0D08,
    SENINF_TEE_REG_ADDR_SENINF14_MUX_CTRL_0       = 0x0D00,
    SENINF_TEE_REG_ADDR_SENINF14_MUX_CTRL_1       = 0x0D04,
    SENINF_TEE_REG_ADDR_SENINF14_MUX_OPT          = 0x0D08,
    SENINF_TEE_REG_ADDR_SENINF15_MUX_CTRL_0       = 0x0D00,
    SENINF_TEE_REG_ADDR_SENINF15_MUX_CTRL_1       = 0x0D04,
    SENINF_TEE_REG_ADDR_SENINF15_MUX_OPT          = 0x0D08,
    SENINF_TEE_REG_ADDR_SENINF16_MUX_CTRL_0       = 0x0D00,
    SENINF_TEE_REG_ADDR_SENINF16_MUX_CTRL_1       = 0x0D04,
    SENINF_TEE_REG_ADDR_SENINF16_MUX_OPT          = 0x0D08,
    SENINF_TEE_REG_ADDR_SENINF17_MUX_CTRL_0       = 0x0D00,
    SENINF_TEE_REG_ADDR_SENINF17_MUX_CTRL_1       = 0x0D04,
    SENINF_TEE_REG_ADDR_SENINF17_MUX_OPT          = 0x0D08,
    SENINF_TEE_REG_ADDR_SENINF18_MUX_CTRL_0       = 0x0D00,
    SENINF_TEE_REG_ADDR_SENINF18_MUX_CTRL_1       = 0x0D04,
    SENINF_TEE_REG_ADDR_SENINF18_MUX_OPT          = 0x0D08,
    SENINF_TEE_REG_ADDR_SENINF19_MUX_CTRL_0       = 0x0D00,
    SENINF_TEE_REG_ADDR_SENINF19_MUX_CTRL_1       = 0x0D04,
    SENINF_TEE_REG_ADDR_SENINF19_MUX_OPT          = 0x0D08,
    SENINF_TEE_REG_ADDR_SENINF20_MUX_CTRL_0       = 0x0D00,
    SENINF_TEE_REG_ADDR_SENINF20_MUX_CTRL_1       = 0x0D04,
    SENINF_TEE_REG_ADDR_SENINF20_MUX_OPT          = 0x0D08,
    SENINF_TEE_REG_ADDR_SENINF21_MUX_CTRL_0       = 0x0D00,
    SENINF_TEE_REG_ADDR_SENINF21_MUX_CTRL_1       = 0x0D04,
    SENINF_TEE_REG_ADDR_SENINF21_MUX_OPT          = 0x0D08,
    SENINF_TEE_REG_ADDR_SENINF22_MUX_CTRL_0       = 0x0D00,
    SENINF_TEE_REG_ADDR_SENINF22_MUX_CTRL_1       = 0x0D04,
    SENINF_TEE_REG_ADDR_SENINF22_MUX_OPT          = 0x0D08,
} SENINF_TEE_REG_ADDR;

typedef struct {
	uint32_t           SENINF_TEE_MUX_CTRL_0;
	uint32_t           SENINF_TEE_MUX_CTRL_1;
	uint32_t           SENINF_TEE_MUX_OPT;
} SENINF_TEE_REG_MUX;

typedef struct {
	uint32_t           SENINF_TEE_CAM_MUX_CTRL;
} SENINF_TEE_REG_CAM_MUX;
typedef struct {
	uint32_t REG_SENINF_TOP_MUX_CTRL_0;
	uint32_t REG_SENINF_TOP_MUX_CTRL_1;
	uint32_t REG_SENINF_TOP_MUX_CTRL_2;
	uint32_t REG_SENINF_TOP_MUX_CTRL_3;
	uint32_t REG_SENINF_TOP_MUX_CTRL_4;
	uint32_t REG_SENINF_TOP_MUX_CTRL_5;
	SENINF_TEE_REG_CAM_MUX  seninf_cam_mux[SENINF_CAM_MUX_MAX_NUM];
	SENINF_TEE_REG_MUX  seninf_mux[SENINF_MUX_MAX_NUM];
} SENINF_TEE_REG;

#define SENINF_TEE_REG_GET_ADDR(reg) (SENINF_TEE_REG_ADDR_##reg + SENINF_TEE_REG_ADDR_BASE)

#endif

