/********************************************************************************************
 *     LEGAL DISCLAIMER
 *
 *     (Header of MediaTek Software/Firmware Release or Documentation)
 *
 *     BY OPENING OR USING THIS FILE, BUYER HEREBY UNEQUIVOCALLY ACKNOWLEDGES AND AGREES
 *     THAT THE SOFTWARE/FIRMWARE AND ITS DOCUMENTATIONS ("MEDIATEK SOFTWARE") RECEIVED
 *     FROM MEDIATEK AND/OR ITS REPRESENTATIVES ARE PROVIDED TO BUYER ON AN "AS-IS" BASIS
 *     ONLY. MEDIATEK EXPRESSLY DISCLAIMS ANY AND ALL WARRANTIES, EXPRESS OR IMPLIED,
 *     INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR
 *     A PARTICULAR PURPOSE OR NONINFRINGEMENT. NEITHER DOES MEDIATEK PROVIDE ANY WARRANTY
 *     WHATSOEVER WITH RESPECT TO THE SOFTWARE OF ANY THIRD PARTY WHICH MAY BE USED BY,
 *     INCORPORATED IN, OR SUPPLIED WITH THE MEDIATEK SOFTWARE, AND BUYER AGREES TO LOOK
 *     ONLY TO SUCH THIRD PARTY FOR ANY WARRANTY CLAIM RELATING THERETO. MEDIATEK SHALL ALSO
 *     NOT BE RESPONSIBLE FOR ANY MEDIATEK SOFTWARE RELEASES MADE TO BUYER'S SPECIFICATION
 *     OR TO CONFORM TO A PARTICULAR STANDARD OR OPEN FORUM.
 *
 *     BUYER'S SOLE AND EXCLUSIVE REMEDY AND MEDIATEK'S ENTIRE AND CUMULATIVE LIABILITY WITH
 *     RESPECT TO THE MEDIATEK SOFTWARE RELEASED HEREUNDER WILL BE, AT MEDIATEK'S OPTION,
TO REVISE OR REPLACE THE MEDIATEK SOFTWARE AT ISSUE, OR REFUND ANY SOFTWARE LICENSE
 *     FEES OR SERVICE CHARGE PAID BY BUYER TO MEDIATEK FOR SUCH MEDIATEK SOFTWARE AT ISSUE.
 *
 *     THE TRANSACTION CONTEMPLATED HEREUNDER SHALL BE CONSTRUED IN ACCORDANCE WITH THE LAWS
 *     OF THE STATE OF CALIFORNIA, USA, EXCLUDING ITS CONFLICT OF LAWS PRINCIPLES.
 ************************************************************************************************/

#ifndef __SENINF_DRV_CSI_INFO_H__
#define __SENINF_DRV_CSI_INFO_H__

#include "secure_port.h"

typedef enum {
    SENINF_MUX1  = 0x0,
    SENINF_MUX2  = 0x1,
    SENINF_MUX3  = 0x2,
    SENINF_MUX4  = 0x3,
    SENINF_MUX5  = 0x4,
    SENINF_MUX6  = 0x5,
    SENINF_MUX7  = 0x6,
    SENINF_MUX8  = 0x7,
    SENINF_MUX9  = 0x8,
    SENINF_MUX10 = 0x9,
    SENINF_MUX11 = 0xA,
    SENINF_MUX12 = 0xB,
    SENINF_MUX13 = 0xC,
    SENINF_MUX14 = 0xD,
    SENINF_MUX15 = 0xE,
    SENINF_MUX16 = 0xF,
    SENINF_MUX17 = 0x10,
    SENINF_MUX18 = 0x11,
    SENINF_MUX19 = 0x12,
    SENINF_MUX20 = 0x13,
    SENINF_MUX21 = 0x14,
    SENINF_MUX22 = 0x15,
    SENINF_MUX_NUM,
    SENINF_MUX_ERROR = 0xFF,
} SENINF_MUX_ENUM;

typedef enum {
    SENINF_1,
    SENINF_2,
    SENINF_3,
    SENINF_4,
    SENINF_5,
    SENINF_6,
    SENINF_7,
    SENINF_8,
    SENINF_9,
    SENINF_10,
    SENINF_11,
    SENINF_12,
    SENINF_NUM,
    SENINF_ENUM_ERROR = 0xF,
} SENINF_ENUM;

typedef enum{
    SENINF_CAM_MUX0,
    SENINF_CAM_MUX1,
    SENINF_CAM_MUX2,
    SENINF_CAM_MUX3,
    SENINF_CAM_MUX4,
    SENINF_CAM_MUX5,
    SENINF_CAM_MUX6,
    SENINF_CAM_MUX7,
    SENINF_CAM_MUX8,
    SENINF_CAM_MUX9,
    SENINF_CAM_MUX10,
    SENINF_CAM_MUX11,
    SENINF_CAM_MUX12,
    SENINF_CAM_MUX13,
    SENINF_CAM_MUX14,
    SENINF_CAM_MUX15,
    SENINF_CAM_MUX16,
    SENINF_CAM_MUX17,
    SENINF_CAM_MUX18,
    SENINF_CAM_MUX19,
    SENINF_CAM_MUX20,
    SENINF_CAM_MUX21,
    SENINF_CAM_MUX22,
    SENINF_CAM_MUX_NUM,
    SENINF_CAM_MUX_ERR = 0xff
}SENINF_CAM_MUX_ENUM;



typedef enum { //0:CSI2(2.5G), 3: parallel, 8:NCSI2(1.5G)
    CSI2            = 0x0, /* 2.5G support */
    TEST_MODEL      = 0x1,
    CCIR656         = 0x2,
    PARALLEL_SENSOR = 0x3,
    SERIAL_SENSOR   = 0x4,
    HD_TV           = 0x5,
    EXT_CSI2_OUT1   = 0x6,
    EXT_CSI2_OUT2   = 0x7,
    MIPI_SENSOR     = 0x8,/* 1.5G support */
    VIRTUAL_CHANNEL_1 	= 0x9,
    VIRTUAL_CHANNEL_2 	= 0xA,
    VIRTUAL_CHANNEL_3 	= 0xB,
    VIRTUAL_CHANNEL_4 	= 0xC,
    VIRTUAL_CHANNEL_5 	= 0xD,
    VIRTUAL_CHANNEL_6 	= 0xE,
} SENINF_SOURCE_ENUM;

typedef enum {
    CUSTOM_CFG_SECURE_NONE,
    CUSTOM_CFG_SECURE_M0
} CUSTOM_CFG_SECURE;

typedef struct {
    CUSTOM_CFG_CSI_PORT port;
    SENINF_ENUM         seninf;
    SENINF_SOURCE_ENUM  srcType;
} SENINF_CSI_INFO;


#endif

